# Generated by Django 5.2.7 on 2025-11-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraryitem',
            old_name='day',
            new_name='days',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='cost',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
    ]
