# Generated by Django 5.2.7 on 2025-11-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_rename_day_itineraryitem_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraryitem',
            old_name='days',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='start_time',
        ),
    ]
