# Generated by Django 5.2.7 on 2025-10-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('SEK', 'SEK — Swedish krona'), ('USD', 'USD — US dollar'), ('EUR', 'EUR — Euro'), ('PHP', 'PHP — Philippine peso'), ('GBP', 'GBP — British pound'), ('JPY', 'JPY — Japanese yen'), ('CNY', 'CNY — Chinese yuan'), ('AUD', 'AUD — Australian dollar'), ('CAD', 'CAD — Canadian dollar'), ('CHF', 'CHF — Swiss franc'), ('NZD', 'NZD — New Zealand dollar')], default='SEK', max_length=8),
        ),
    ]
